services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airportdb
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-proot"]
      interval: 10s
      retries: 5
