spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airportdb
    username: app
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080
