spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airport_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  spring:
    jpa:
      hibernate:
        ddl-auto: create
    sql:
      init:
        mode: always

